services:
  server:
    build: .
    restart: on-failure:5
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - PORT=${PORT}
      - MAX_RATE_LIMIT=${MAX_RATE_LIMIT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
