services:
  server:
    build: .
    restart: on-failure:5
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - PORT=${PORT}
      - DB_CONN=${DB_CONN}
      - MAX_RATE_LIMIT=${MAX_RATE_LIMIT}
