services:
  server:
    build: .
    restart: on-failure:5
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - PORT=${PORT}
      - DB_CONN=${DB_CONN}
      - MAX_RATE_LIMIT=${MAX_RATE_LIMIT}
    networks:
      - "mynet"

  database:
    image: "mysql:latest"
    container_name: "db-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "lila_db"
      MYSQL_ROOT_PASSWORD: "lila_db"
    volumes:
      - "./resources/db.sql:/docker-entrypoint-initdb.d/db.sql"
    networks:
      - "mynet"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 2

networks:
  mynet:
    driver: "bridge"